# Generated by Django 4.1.13 on 2024-09-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('intensity', models.FloatField()),
                ('likelihood', models.FloatField()),
                ('relevance', models.FloatField()),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('pestle', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('insight', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Insights',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
